### ISSUE TITLE
Shell Flyout Footer

### ISSUE THREAD

**Issue by sboh1214** [MicrosoftDocs/xamarin-docs.ko-kr#50]
Can I make a footer in shell flyout?

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: e8eebbec-c116-fa16-14f3-83e5905e28b2
* Version Independent ID: 9124edfa-2df2-0ef2-6722-0efc0e1134da
* Content: [Xamarin.Forms Shell - Xamarin](https://docs.microsoft.com/ko-kr/xamarin/xamarin-forms/app-fundamentals/shell?tabs=android)
* Content Source: [docs/xamarin-forms/app-fundamentals/shell.md](https://github.com/MicrosoftDocs/xamarin-docs.ko-KR/blob/live/docs/xamarin-forms/app-fundamentals/shell.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by CeciAc** [comment]
Hello, @sboh1214 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback/제품 피드백 제공"
 at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
