### ISSUE TITLE
window 가 소문자로 되어 있습니다. 

### ISSUE THREAD

**Issue by daesang** [MicrosoftDocs/xamarin-docs.ko-kr#52]
[여기에 피드백 입력]
public class AppDelegate : UIApplicationDelegate
{
    public override UIWindow Window
            {
                get;
                set;
            }

    public override bool FinishedLaunching(UIApplication app, NSDictionary options)
    {
        // create a new window instance based on the screen size
        window = new UIWindow(UIScreen.MainScreen.Bounds);

        // make the window visible
        window.MakeKeyAndVisible();

        return true;
    }
}

window 가 소문자로 되어 있습니다. 
---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 08c274f5-e72f-067b-6cdc-81c50acc7616
* Version Independent ID: 5b0d048a-83d0-98a4-d4d0-027befc40365
* Content: [Xamarin.iOS에서 코드로 iOS 사용자 인터페이스 만들기 - Xamarin](https://docs.microsoft.com/ko-kr/xamarin/ios/app-fundamentals/ios-code-only?tabs=windows#feedback)
* Content Source: [docs/ios/app-fundamentals/ios-code-only.md](https://github.com/MicrosoftDocs/xamarin-docs.ko-KR/blob/live/docs/ios/app-fundamentals/ios-code-only.md)
* Product: **xamarin**
* Technology: **xamarin-ios**
* GitHub Login: @lobrien
* Microsoft Alias: **laobri**

**Comment by srvbpigh** [comment]
Hello, @daesang
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/xamarin-docs #1977](https://github.com/MicrosoftDocs/xamarin-docs/issues/1977) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
안녕하세요, @daesang 님. 
 귀하의 기여에 매우 감사 드립니다. 귀하의 피드백은 원본 설명서와 관련되어 있습니다. 
 따라서 이 문제를 영어 리포지토리에 마이그레이션하고 있습니다. 여기 - https://github.com/MicrosoftDocs/xamarin-docs/issues/1977 에서 문제 상태를 확인하세요. 
 당사 문서에 대한 귀하의 기여에 진심으로 감사 드립니다.  
 감사합니다. 
Microsoft DOCS 국제 팀
