### ISSUE TITLE
submitButton의 TouchUpInside 이벤트가 작동되지 않는다.

### ISSUE THREAD

**Issue by daesang** [MicrosoftDocs/xamarin-docs.ko-kr#53]
[여기에 피드백 입력]

//var submitButton = UIButton.FromType (UIButtonType.RoundedRect);
var submitButton = new UIButton(UIButtonType.RoundedRect);
submitButton.Frame = new CGRect (10, 170, w - 20, 44);
submitButton.SetTitle ("Submit", UIControlState.Normal);

submitButton.TouchUpInside += (sender, e) => {
    Console.WriteLine ("Submit button pressed");
};

View.AddSubview(submitButton);

---
var submitButton = new UIButton(UIButtonType.RoundedRect);
이렇게 해야 TouchUpInside 이벤트가 작동합니다.

#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 08c274f5-e72f-067b-6cdc-81c50acc7616
* Version Independent ID: 5b0d048a-83d0-98a4-d4d0-027befc40365
* Content: [Xamarin.iOS에서 코드로 iOS 사용자 인터페이스 만들기 - Xamarin](https://docs.microsoft.com/ko-kr/xamarin/ios/app-fundamentals/ios-code-only?tabs=windows#feedback)
* Content Source: [docs/ios/app-fundamentals/ios-code-only.md](https://github.com/MicrosoftDocs/xamarin-docs.ko-KR/blob/live/docs/ios/app-fundamentals/ios-code-only.md)
* Product: **xamarin**
* Technology: **xamarin-ios**
* GitHub Login: @lobrien
* Microsoft Alias: **laobri**

**Comment by srvbpigh** [comment]
Hello, @daesang
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
안녕하세요, @daesang 님. 
 귀하의 기여에 매우 감사 드립니다. 당사의 팀만이 설명서와 관련된 피드백에 응답할 수 있습니다. 
 DOCS 페이지 하단에 있는 "제품 피드백 제공" 버튼을 사용하여 귀하의 제품 피드백을 기록해주세요. 
 설명서와 관련된 피드백이 있는 경우 이 채널을 통해 자유롭게 기록해주세요. 
 당사 문서에 대한 귀하의 기여에 진심으로 감사 드립니다.  
 감사합니다.
Microsoft DOCS 국제 팀
