### ISSUE TITLE
한글 번역 오류

### ISSUE THREAD

**Issue by daesang** [MicrosoftDocs/xamarin-docs.ko-kr#54]
[여기에 피드백 입력]
컴파일 시 Xamarin.ios는 다음 XML 요소를 Androidmanifest 에 삽입 하 여 서비스를 등록 합니다. 즉, xamarin.ios에서 서비스에 대 한 무작위 이름을 생성 합니다.

-> 
컴파일 시 Xamarin.Android는 다음 XML 요소를 Androidmanifest 에 삽입 하 여 서비스를 등록 합니다. 즉, Xamarin.Android에서 서비스에 대 한 무작위 이름을 생성 합니다.
---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 4c7b8d9b-b6a9-62f8-28fb-971bb39d4c99
* Version Independent ID: 7893ffeb-dc5c-8cb4-1e05-31315d4adf31
* Content: [서비스 만들기 - Xamarin](https://docs.microsoft.com/ko-kr/xamarin/android/app-fundamentals/services/creating-a-service/)
* Content Source: [docs/android/app-fundamentals/services/creating-a-service/index.md](https://github.com/MicrosoftDocs/xamarin-docs.ko-KR/blob/live/docs/android/app-fundamentals/services/creating-a-service/index.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by srvbpigh** [comment]
Hello, @daesang
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
안녕하세요, @daesang 님.  
 피드백을 주셔서 감사합니다. 
 당사의 언어 팀이 귀하의 언어 제안을 검토하고 수용했습니다. 귀하의 피드백을 반영하여 Docs 사이트의 업데이트된 문서의 다음 페이지 https://docs.microsoft.com/ko-kr/xamarin/android/app-fundamentals/services/creating-a-service/ 에 게시했습니다.  
 당사의 문서에 대한 귀하의 기여에 진심으로 감사 드리며 소중한 피드백을 계속 주시기 바랍니다. 
 감사합니다. 
Microsoft DOCS 국제 팀
