### ISSUE TITLE
Wrong from the title

### ISSUE THREAD

**Issue by TaejunPark** [MicrosoftDocs/xamarin-docs.ko-kr#58]
[여기에 피드백 입력]
In English version, it saids xamarin.forms but in korean version it saids xamarin.ios. Korean guy like me feels xamarin should implement ios and android separately from the beginning 

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: fe23a45b-384d-31ed-917a-4d7e60158778
* Version Independent ID: dd49e8ac-5a48-8cb3-36ae-8af9c40a880d
* Content: [Xamarin.ios Controls 클래스 계층 구조 - Xamarin](https://docs.microsoft.com/ko-kr/xamarin/xamarin-forms/internals/class-hierarchy)
* Content Source: [docs/xamarin-forms/internals/class-hierarchy.md](https://github.com/MicrosoftDocs/xamarin-docs.ko-kr/blob/live/docs/xamarin-forms/internals/class-hierarchy.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by srvbpigh** [comment]
Hello, @TaejunPark
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello @TaejunPark 

Thank you for your contribution. 

Contributions on translation problems against machine-translated content are currently not accepted. 

We value your feedback and suggestions on human translated content, which is used to train the machine translation engines, so over time, your contributions will improve the quality of both human and machine translations. 

Human translated topics can be distinguished from machine-translated topics by the ms.translationtype metadata value “HT” (versus “MT” for machine translated) in the header of each content file. 

Many thanks for your support. 

Microsoft DOCS Global Experience Team

**Comment by JasonCard** [comment]
Hi @TaejunPark 

Thank you for your feedback.
We're following up to fix this over-localization issue in all files.


Best regards,
Jason
